### ISSUE TITLE
Make use of karma.conf file

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-karma-runner#7]
A lot of users expect `karma.conf.js` settings to be mirrored in stryker. We should add this feature using the ConfigWriter interface.

We should either completely remove the current `karmaConfig` overrides method and only except a string, or we should support both a string (location of the `karma.conf.js` file). @simondel which one would you prefer? 

In order for this to work https://github.com/stryker-mutator/stryker/issues/148 needs to be fixed as well. Otherwise the current working directory would not be in sync with all preprocessor paths and such.

**Comment by simondel** [comment]
Implemented with #10 

Still has to be documented

**Comment by simondel** [comment]
Documented with #15
